name: marquee
description: '⏩ A Flutter widget that scrolls its child infinitely. Features vertical and horizontal scrolling as well as custom velocities.'
version: 0.1.0
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/marquee

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
